name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true

      - name: Auto-match Firebase Package Name and MinSDK
        run: |
          PACKAGE_NAME=$(grep -o '"package_name": *"[^"]*"' android/app/google-services.json | head -1 | cut -d'"' -f4)
          echo "Detected Firebase Package: $PACKAGE_NAME"
          find android/ -type f -name "build.gradle" -exec sed -i "s/applicationId .*/applicationId \"$PACKAGE_NAME\"/g" {} +
          find android/ -type f -name "build.gradle" -exec sed -i "s/namespace .*/namespace \"$PACKAGE_NAME\"/g" {} +
          find android/ -type f -name "build.gradle" -exec sed -i 's/minSdkVersion 21/minSdkVersion 23/g' {} +
          find android/ -type f -name "build.gradle" -exec sed -i 's/flutter.minSdkVersion/23/g' {} +
          find android/ -type f -name "AndroidManifest.xml" -exec sed -i "s/package=\"[^\"]*\"/package=\"$PACKAGE_NAME\"/g" {} +

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BrainXperts-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
